<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>FsocietyNet</AssemblyName>
    <RootNamespace>FsocietyNet</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.1" />
  </ItemGroup>

  <!-- Вшитые бинарники AmneziaWG. Файлы должны лежать в FsocietyNet/Resources/ -->
  <ItemGroup>
    <EmbeddedResource Include="Resources\amneziawg.exe" Condition="Exists('Resources\amneziawg.exe')" />
    <EmbeddedResource Include="Resources\wintun.dll"    Condition="Exists('Resources\wintun.dll')" />
  </ItemGroup>
</Project>
